### ISSUE TITLE
Feat: Precompiled binaries ala tailwindcss-rails

### ISSUE THREAD

**Issue by henrikbjorn** [hardpixel/mrml-ruby#1]
**Is your feature request related to a problem? Please describe.**
Yes. Instead of having to install Rust on production servers to install the gem and to increase install speed. it would be beneficial to have precompiled mrml binaries ala tailwindcss-rails does

**Describe the solution you'd like**
Precompile the gem extension

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by henrikbjorn** [comment]
This gem does it somehow https://github.com/IAPark/tiktoken_ruby

**Comment by paulgoetze** [comment]
Hey @jonian, are you already working on that? Else I'd be happy to take a look at how to provide precompiled binaries for mrml-ruby, if you are okay with that?

**Comment by jonian** [comment]
Hi @paulgoetze, no I'm not working on it. It would be great if you can submit a PR. Thanks!

**Comment by jonian** [comment]
I think it should be implemented using [oxidize-rb/actions](https://github.com/oxidize-rb/actions/blob/main/cross-gem/readme.md). An example workflow in the [polars-ruby](https://github.com/ankane/polars-ruby/blob/master/ext/polars/Cargo.toml) gem.

**Comment by paulgoetze** [comment]
:+1: Alright, thanks, @jonian, then I'll take a look.

**Comment by paulgoetze** [comment]
@jonian ping, just to make sure you saw the pull request :)
Let me know if you need anything else or if there's anything I can help with to get the pre-compiled gems released.

**Comment by jonian** [comment]
I have released a new version with the cross-compiled gems. Thank you for the help @paulgoetze!
The cross-compiled gems support only ruby 3.0, 3.1 and 3.2.
