### ISSUE TITLE
Precompiled binaries not compatible with ruby 3.3

### ISSUE THREAD

**Issue by tijn-moneybird** [hardpixel/mrml-ruby#9]
**Is your feature request related to a problem? Please describe.**
The precompile binaries of mrml are only included up to ruby 3.2.

**Describe the solution you'd like**
Could the precompiled binaries of mrml be made available for ruby 3.3?

**Comment by jonian** [comment]
Version 1.4.3 with precompiled binaries for ruby 3.3 has been released.
